export interface Product {
  id: string;
  title: string;
  description: string;
  category: string;
  price: number;
  image: string;
  rating: number;
  reviews: number;
  details: string;
  file_url?: string;
}

export const products: Product[] = [
  {
    id: '1',
    title: 'Structural Steel Design to Eurocode 3 and AISC Specifications',
    description: 'Comprehensive guide to steel structure design',
    category: 'Construction Documents',
    price: 49.99,
    image: '/books/book1.png',
    rating: 5,
    reviews: 128,
    details: 'This comprehensive book covers all aspects of structural steel design following Eurocode 3 and AISC standards. Perfect for engineers and construction professionals.',
  },
  {
    id: '2',
    title: 'The Behavior of Multi-Storey Steel Framed Buildings in Fire',
    description: 'Fire safety and steel frame behavior',
    category: 'M&E Documents',
    price: 59.99,
    image: '/books/book2.png',
    rating: 4,
    reviews: 95,
    details: 'Deep dive into how steel structures behave during fire incidents with practical safety guidelines.',
  },
  {
    id: '3',
    title: 'Structural Fire Performance of Steel Portal Frame Buildings',
    description: 'Portal frame design and fire resistance',
    category: 'Architectural Documentation',
    price: 47.99,
    image: '/books/book3.png',
    rating: 5,
    reviews: 156,
    details: 'Essential resource for designing steel portal frames with fire safety considerations.',
  },
  {
    id: '4',
    title: 'Steel and Composite Structures - Behavior and Design for Fire Safety',
    description: 'Composite structure design and analysis',
    category: 'Construction Documents',
    price: 67.99,
    image: '/books/book4.png',
    rating: 5,
    reviews: 203,
    details: 'Complete guide to steel and composite structure design with emphasis on fire safety requirements.',
  },
  {
    id: '5',
    title: 'Construction Management Handbook',
    description: 'Project management and site supervision',
    category: 'Construction Management',
    price: 42.99,
    image: '/books/book1.png',
    rating: 4,
    reviews: 87,
    details: 'Practical handbook for construction managers covering planning, scheduling, and site management.',
  },
  {
    id: '6',
    title: 'Building Materials: Properties and Applications',
    description: 'Comprehensive material properties reference',
    category: 'Building Materials',
    price: 39.99,
    image: '/books/book2.png',
    rating: 4,
    reviews: 142,
    details: 'Detailed reference guide on building materials, their properties, and applications in construction.',
  },
  {
    id: '7',
    title: 'Foundation Design and Construction',
    description: 'Foundation engineering principles',
    category: 'Foundation Engineering',
    price: 54.99,
    image: '/books/book3.png',
    rating: 5,
    reviews: 118,
    details: 'Complete guide to foundation design, soil mechanics, and construction techniques.',
  },
  {
    id: '8',
    title: 'Concrete Structures: Design and Construction',
    description: 'Reinforced and prestressed concrete design',
    category: 'Structural Design',
    price: 49.99,
    image: '/books/book4.png',
    rating: 5,
    reviews: 176,
    details: 'Comprehensive guide to reinforced concrete design with modern construction methods.',
  },
  {
    id: '9',
    title: 'Geotechnical Engineering Principles',
    description: 'Soil mechanics and geotechnical analysis',
    category: 'Geotechnical',
    price: 52.99,
    image: '/books/book1.png',
    rating: 4,
    reviews: 93,
    details: 'Essential principles of soil mechanics and geotechnical engineering applications.',
  },
  {
    id: '10',
    title: 'Water Resource Engineering',
    description: 'Hydraulics and water management',
    category: 'Civil Infrastructure',
    price: 45.99,
    image: '/books/book2.png',
    rating: 4,
    reviews: 76,
    details: 'Practical guide to water resource management and hydraulic engineering.',
  },
  {
    id: '11',
    title: 'Transportation Engineering Fundamentals',
    description: 'Road and traffic engineering basics',
    category: 'Transportation',
    price: 43.99,
    image: '/books/book3.png',
    rating: 4,
    reviews: 65,
    details: 'Comprehensive resource for transportation and road engineering professionals.',
  },
  {
    id: '12',
    title: 'Environmental Engineering and Sustainability',
    description: 'Environmental impact and green building',
    category: 'Environmental',
    price: 40.99,
    image: '/books/book4.png',
    rating: 4,
    reviews: 104,
    details: 'Guide to environmental considerations in civil engineering projects and sustainable practices.',
  },
];

export const categories = [
  'All Categories',
  'Architectural Documentation',
  'Architecture English',
  'Architecture Student Project',
  'Vietnamese Texture Books',
  'English Texture Books',
  'M&E Documents',
  'Construction Documents',
  'Construction Economics Document',
  'Construction Software',
  'Construction spreadsheet',
  'Building Standards',
  'Building Materials',
  'Traffic Works',
];
